# setup:
#
#     npm install [-g] eslint    \
#         eslint-config-standard \
#         eslint-plugin-standard \
#         eslint-plugin-import   \
#         eslint-plugin-node     \
#         eslint-plugin-promise
#
# (eslint-plugin-import, eslint-plugin-node, and eslint-plugin-promise
# are peer dependencies of eslint-config-standard)

env:
  browser: true
  commonjs: true
  jquery: true
  node: true

parser: babel-eslint

plugins:
  - standard # not the community standard, but close enough

extends:
  - standard

# override standard's defaults
rules:
  # require 4 spaces
  indent:
    - error
    - 4

  # don't care if multiple vars are initialised with
  # a single statement
  one-var: 0

  # only allow trailing commas in multi-line expressions
  comma-dangle:
    - error
    -
      arrays: only-multiline
      objects: only-multiline
      functions: only-multiline
      imports: never
      exports: never

  # prefer
  #
  #     function foo () { ... }
  #
  # over
  #
  #     var foo = function () { ... }
  #
  # but allow arrow functions e.g.
  #
  #     const foo = bar => baz

  func-style:
    - error
    - declaration
    -
      allowArrowFunctions: true

  # don't require operators to be consistently placed at the beginning/end
  # of lines: it varies according to the lines
  operator-linebreak: 0

  # prohibit multiple spaces unless they're used to align requires, imports,
  # or object literals
  key-spacing: 0
  no-multi-spaces:
    - error
    -
      exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true
