# setup:
#
#     npm install [-g] eslint    \
#         eslint-config-standard \
#         eslint-plugin-standard \
#         eslint-plugin-import   \
#         eslint-plugin-node     \
#         eslint-plugin-promise

env:
  browser: true
  commonjs: true
  jasmine: true
  jquery: true
  node: true
  phantomjs: true
  protractor: true

parser: babel-eslint

plugins:
  - standard # not the community standard, but close enough

extends:
  - standard

# override standard's defaults
rules:
  # require 4 spaces
  indent:
    - error
    - 4

  # don't care either way about semi-colons
  semi: 0

  # don't care if multiple vars are initialised with
  # a single statement
  one-var: 0

  # only allow trailing commas in arrays and objects
  # (i.e. avoid using/keeping them in function parameters,
  # which aren't supported prior to ES7)
  comma-dangle:
    - error
    -
      arrays: only-multiline
      objects: only-multiline
      imports: never
      exports: never
      functions: never

  # prefer
  #
  #     function foo () { ... }
  #
  # over
  #
  #     var foo = function () { ... }
  #
  # but allow arrow functions e.g.
  #
  #     const foo = bar => baz

  func-style:
    - error
    - declaration
    -
      allowArrowFunctions: true

  # prefer:
  #
  #     foo ?
  #         bar :
  #         baz
  #
  # over:
  #
  #     foo
  #         ? bar
  #         : baz
  #
  operator-linebreak:
    - error
    - after

  # prohibit multiple spaces unless they're used to align requires, imports,
  # or object literals
  key-spacing: 0
  no-multi-spaces:
    - error
    -
      exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true
